import seedJson from "./europe500SeedData.json";
import type { EuropeSeedRow } from "./europe500Seed.types";

/** European countries pool (filters / legacy helpers). */
export const EU_COUNTRY_POOL = [
  "France",
  "Italy",
  "Spain",
  "Germany",
  "United Kingdom",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Portugal",
  "Greece",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Ireland",
  "Croatia",
  "Slovenia",
  "Luxembourg",
  "Malta",
  "Cyprus",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Slovakia",
  "Bulgaria",
] as const;

/** DB `stateSlug` for all Europe-list rows — URLs use `/top-restaurants/Europe/[countrySlug]/[nameSlug]`. */
export const EUROPE_REGION_STATE_SLUG = "europe";

/** Generated by `npx tsx scripts/build-europe500-wikidata.ts` — curated top venues + synthetic fill to 500. */
export const EUROPE_500_SEED = seedJson as EuropeSeedRow[];

export type { EuropeSeedRow } from "./europe500Seed.types";
